### PR TITLE
misc cleanup

### PR DESCRIPTION
**Pull request by pwinckles**
1. Updates all dependencies to their latest versions
2. Precompiles a few regexes used for splitting
3. Corrects my info

As far as I can think of right now, these are the last changes that I wanted to get in before making the 1.5.0 release.

### CODE REVIEW

**Comment by pwinckles** [comment]
Can one of you approve the db tests? Again, I'm not sure why it's wanting approval for these. I upgraded the drivers here, so it would be good to run them.

**Comment by sprater** [comment]
Will do

**Comment by MormonJesus69420** [comment]
Hi, sorry to comment on a closed merge request, but I was wondering what's the reasoning behind changing the split:
```java
var parts = sidecarContents.split("\\s"); // this
var parts = WHITESPACE.split(sidecarContents); // to this
```
Does it offer some performance benefit, better code safety, or just stylistic choice?

**Comment by pwinckles** [comment]
> Hi, sorry to comment on a closed merge request, but I was wondering what's the reasoning behind changing the split:
> 
> ```java
> var parts = sidecarContents.split("\\s"); // this
> var parts = WHITESPACE.split(sidecarContents); // to this
> ```
> 
> Does it offer some performance benefit, better code safety, or just stylistic choice?

@MormonJesus69420, it is for performance. I perhaps should have put a limit on the split too, thinking about it again. You have to be careful with Java's `String.split()` and `String.replaceAll()`. They both take regex strings which they will compile to `Patterns` on every invocation. `split()` does inspect the regex to see if it can cheat an not compile it if it's just a split on a literal character, but `replaceAll()` does not have a similar optimization. So, long story short, if you want to split/replace on a regex, you should precomile the regex like this PR does, and if you want to replace string literals you should use `String.replace()`, which will still replace all matches -- you'd only ever want to use `String.replaceAll()` if you don't know the regex you're going to replace on before hand.

**Pull request merged**
